spring:
  config:
    activate:
      on-profile: onsemi-oracle
  liquibase:
    change-log: classpath:db/changelog/db.changelog-1.0.xml

# Oracle application DB used for staging and dispatch in the onsemi environment.
refdb:
  host: exndev-db.onsemi.com
  port: 1739
  # Use service-style URL as requested: exndev-db.onsemi.com:1739/EXNDEV.onsemi.com
  service: EXNDEV.onsemi.com
  user: refdb
  password: "XBfjCq#$1542FFz"
  staging-table: SENDER_STAGE
  pool:
    max-size: 5
    min-idle: 1
  dispatch:
    per-send: 100
    interval-ms: 60000

external-db:
  hikari:
    maximum-pool-size: 10
    minimum-idle: 1
    connection-timeout-ms: 15000
    idle-timeout-ms: 600000
    validation-timeout-ms: 5000
  cache:
    max-pools: 50
    expire-after-access-minutes: 60

reloader:
  dbconn:
    yaml:
      path: classpath:dbconnections.yml