server:
  port: 8080

spring:
  config:
    activate:
      on-profile: onsemi-oracle
  autoconfigure:
    # Override base exclusion: re-enable Liquibase auto-configuration in this profile
    exclude: []
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-1.0.xml
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.OracleDialect
      hibernate.jdbc.time_zone: UTC
  datasource:
    # Use refdb.* properties below via placeholders so the canonical values live in refdb
    url: "jdbc:oracle:thin:@//${refdb.host}:${refdb.port}/${refdb.service}"
    username: ${refdb.user}
    password: ${refdb.password}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: ${refdb.pool.max-size:5}
      minimum-idle: ${refdb.pool.min-idle:1}
      connection-timeout: 15000
      idle-timeout: 600000
      validation-timeout: 5000
  mail:
    host: mailhost.onsemi.com      # your SMTP host (e.g. smtp.sendgrid.net)
    port: 25                      # internal SMTP relay, no auth/STARTTLS
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

# Oracle application DB used for staging and dispatch in the onsemi environment.
refdb:
  host: exndev-db.onsemi.com
  port: 1739
  # Use service-style URL as requested: exndev-db.onsemi.com:1739/EXNDEV.onsemi.com
  service: EXNDEV.onsemi.com
  user: refdb
  password: "XBfjCq#$1542FFz"
  auth-bootstrap-enabled: true
  bootstrap-admins: "admin"
  staging-table: SENDER_STAGE
  pool:
    max-size: 5
    min-idle: 1
  dispatch:
    per-send: 100
    interval-ms: 60000

external-db:
  hikari:
    maximum-pool-size: 10
    minimum-idle: 1
    connection-timeout-ms: 15000
    idle-timeout-ms: 600000
    validation-timeout-ms: 5000
  cache:
    max-pools: 50
    expire-after-access-minutes: 60

reloader:
  dbconn:
    yaml:
      path: classpath:dbconnections.yml


security:
  ldap:
    enabled: false
  sso:
    enabled: false
  csp:
    relaxed: true

# Optional: from address used when sending automated messages
app:
  mail:
    from: "no-reply@onsemi.com"
    reset-url-base: "http://localhost:4200/reset-password"
# Dev note: in the 'test' profile the app returns reset/verification tokens in HTTP responses