security:
  ldap:
    enabled: true
    urls: ${LDAP_URLS:ldap://ad.onsemi.com:389}
    base: ${LDAP_BASE:dc=onsemi,dc=com}
    manager-dn: ${LDAP_MANAGER_DN:CN=svc_ldap,OU=Service Accounts,DC=onsemi,DC=com}
    manager-password: ${LDAP_MANAGER_PASSWORD:changeme}
    user-search-base: ${LDAP_USER_SEARCH_BASE:OU=Users}
    user-search-filter: ${LDAP_USER_SEARCH_FILTER:(sAMAccountName={0})}

server:
  forward-headers-strategy: framework
