server:
  port: 8080

# JPA / H2 defaults for local development
spring:
  datasource:
    url: jdbc:h2:mem:reloader;DB_CLOSE_DELAY=-1;MODE=Oracle
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

# Liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-1.0.xml
