spring:
  mail:
    host: localhost
    port: 1025
    username: ''
    password: ''
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
app:
  mail:
    from: "no-reply@localhost"
    reset-url-base: "http://localhost:4200/reset-password"
