server:
  port: 8080

# JPA / H2 defaults for local development
spring:
  datasource:
    url: jdbc:h2:mem:reloader;DB_CLOSE_DELAY=-1;MODE=Oracle
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    # Let Hibernate auto-detect the dialect at runtime. Override with
    # -Dspring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
    # when you explicitly want to force Oracle in local runs.
    hibernate:
      ddl-auto: update
    show-sql: true

# Liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-1.0.xml

external-db:
  hikari:
    maximum-pool-size: 10
    minimum-idle: 1
    connection-timeout-ms: 15000
    idle-timeout-ms: 600000
    validation-timeout-ms: 5000
  cache:
    max-pools: 50
    expire-after-access-minutes: 60

refdb:
  host: exndev-db.onsemi.com
  port: 1739
  sid: EXNDEV
  user: refdb
  password: "XBfjCq#$1542FFz"
  staging-table: SENDER_STAGE
  pool:
    max-size: 5
    min-idle: 1
  dispatch:
    per-send: 100
    interval-ms: 60000

reloader:
  dbconn:
    yaml:
      path: classpath:dbconnections.yml
